<meta charset="utf-8" />
        <title>雲玥資訊有限公司, 網站建置 | 網頁設計 </title>
        <meta name="copyright" content="" />
        <meta name="author" content="雲玥資訊有限公司">
		
		
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		
		<!--[if lt IE 9]>
　　　　<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
　　	<![endif]-->


        <!-- html5 for ie--> 
        <!--[if lt IE 9]>
        <script src="js/html5.js"></script> 
        <![endif]-->
        <script src="js/html5-ie8.js"></script> <!-- html5 for ie8--> 


        <!-- css -->
        <link rel="stylesheet" type="text/css" href="css/reset.css">
        <link rel="stylesheet" type="text/css" href="css/font-awesome.css">
        <link rel="stylesheet" type="text/css" href="css/animate.min.css">
        <link rel="stylesheet" type="text/css" href="css/StyleSheet.css">
        <!-- css end -->

        <script type="text/javascript" src="js/fade.js"></script>
		<script src="js/jquery-1.10.2.min.js"></script>